# Generated by Django 4.0.4 on 2022-05-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='product',
        ),
    ]
